const constants = {
  APP_CART_LOCALSTORAGE_KEY: 'xCommerceAppCart',
  SIDEBAR_EXPANDED_LOCALSTORAGE_KEY: 'xCommerceAppSidebarExpanded',
  DISCOUNT_UNIT_PERCENTAGE: 'PERCENTAGE',
  DISCOUNT_UNIT_CURRENCY: 'CURRENCY',
  CURRENCY: '$',
  ACTIVE_DISCOUNT_UNIT: 'PERCENTAGE',
}

export default constants
